apiVersion: v1
kind: Secret
metadata:
  name: db-secret-2022bcd0050
type: Opaque
data:
  DB_USER: YWRtaW4=           # base64 for 'admin'
  DB_PASS: c2VjdXJlcGFzcw==   # base64 for 'securepass'
